import { money } from './blueprintEngine.js'

// --------------------------------------------------------------------------
//  Blueprint → Markdown
// --------------------------------------------------------------------------
export function blueprintToMarkdown(bp) {
  if (!bp) return ''
  const m = (v) => money(bp.currency, v)
  const roadmapDone = bp.roadmap.reduce((s, p) => s + p.tasks.filter((t) => t.done).length, 0)
  const roadmapTotal = bp.roadmap.reduce((s, p) => s + p.tasks.length, 0)

  const lines = []
  lines.push(`# ${bp.concept.productName} — Enterprise Blueprint`)
  lines.push(`_Generated by Aspir by WTS on ${new Date(bp.createdAt).toLocaleString()}_`)
  lines.push('')
  lines.push(`**Business Model:** ${bp.modelLabel}  `)
  lines.push(`**Founder-Market Fit:** ${bp.fitScore}%  `)
  lines.push(`**Target Audience:** ${bp.concept.audience}`)
  lines.push('')
  lines.push('## Executive Summary')
  lines.push(bp.execSummary.elevator)
  lines.push('')
  lines.push('**Primary Revenue Streams:**')
  bp.execSummary.revenueStreams.forEach((r) => lines.push(`- ${r}`))
  lines.push('')
  lines.push(`**Core Differentiator:** ${bp.execSummary.differentiator}`)
  lines.push('')
  lines.push('## Value Proposition & Core Offer')
  lines.push(`**Primary pain solved:** ${bp.concept.corePain}`)
  lines.push('')
  lines.push('| Tier | Price | Includes |')
  lines.push('| --- | --- | --- |')
  bp.economics.priceTiers.forEach((t) =>
    lines.push(`| ${t.name} | ${m(t.price)}${t.cadence} | ${t.features.join('; ')} |`),
  )
  lines.push('')
  lines.push('## Competitive Advantage (Moat)')
  lines.push(bp.moat)
  lines.push('')
  lines.push('## SWOT Analysis')
  lines.push('### Strengths')
  bp.swot.strengths.forEach((s) => lines.push(`- ${s}`))
  lines.push('### Weaknesses')
  bp.swot.weaknesses.forEach((s) => lines.push(`- ${s}`))
  lines.push('### Opportunities')
  bp.swot.opportunities.forEach((s) => lines.push(`- ${s}`))
  lines.push('### Threats')
  bp.swot.threats.forEach((s) => lines.push(`- ${s}`))
  lines.push('')
  lines.push('## Go-To-Market Strategy')
  lines.push(`**Sales motion:** ${bp.gtm.salesMotion}`)
  lines.push('')
  lines.push(`**First 100 customers:** ${bp.gtm.first100}`)
  lines.push('')
  lines.push(`**Content engine:** ${bp.gtm.contentEngine}`)
  lines.push('')
  lines.push('**Acquisition channels:**')
  bp.gtm.channels.forEach((c) => lines.push(`- ${c}`))
  lines.push('')
  lines.push('## Unit Economics & Projections')
  lines.push(`- **CAC:** ${m(bp.economics.cac)}`)
  lines.push(`- **LTV:** ${m(bp.economics.ltv)}`)
  lines.push(`- **LTV:CAC:** ${bp.economics.ltvCacRatio}:1`)
  lines.push(`- **Gross margin:** ${Math.round(bp.economics.grossMargin * 100)}%`)
  lines.push(`- **Break-even:** Month ${bp.economics.breakeven}`)
  lines.push(`- **Projected Year-1 gross revenue:** ${m(bp.economics.year1Gross)}`)
  lines.push('')
  lines.push('## Risk Mitigation Matrix')
  lines.push('| Risk | Severity | Counter-measure |')
  lines.push('| --- | --- | --- |')
  bp.riskMatrix.forEach((r) => lines.push(`| ${r.risk} | ${r.severity} | ${r.mitigation} |`))
  lines.push('')
  lines.push(`## 90-Day Operational Roadmap (${roadmapDone}/${roadmapTotal} complete)`)
  bp.roadmap.forEach((phase) => {
    lines.push(`### ${phase.title} — ${phase.window}`)
    phase.tasks.forEach((t) => lines.push(`- [${t.done ? 'x' : ' '}] ${t.text}`))
    lines.push('')
  })
  return lines.join('\n')
}

// --------------------------------------------------------------------------
//  Roadmap-only export
// --------------------------------------------------------------------------
export function roadmapToMarkdown(bp) {
  if (!bp) return ''
  const lines = [`# ${bp.concept.productName} — 90-Day Roadmap`, '']
  bp.roadmap.forEach((phase) => {
    lines.push(`## ${phase.title} — ${phase.window}`)
    phase.tasks.forEach((t) => lines.push(`- [${t.done ? 'x' : ' '}] ${t.text}`))
    lines.push('')
  })
  return lines.join('\n')
}

// --------------------------------------------------------------------------
//  Download helpers
// --------------------------------------------------------------------------
export function downloadText(filename, text, type = 'text/markdown') {
  const blob = new Blob([text], { type: `${type};charset=utf-8` })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function downloadJSON(filename, obj) {
  downloadText(filename, JSON.stringify(obj, null, 2), 'application/json')
}

export function slugify(s = 'blueprint') {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'blueprint'
}
