// ============================================================================
//  Aspir by WTS — AI Prompt Pack
//  Turns a blueprint into ready-to-paste prompts the founder can drop into any
//  AI assistant to produce real assets (landing page, emails, scripts, etc.).
// ============================================================================

export function generatePromptPack(bp) {
  if (!bp) return []
  const c = bp.concept
  const audience = c.audience
  const product = c.productName
  const pain = c.corePain
  const model = bp.modelLabel
  const channels = bp.gtm.channels.join(', ')
  const tiers = bp.economics.priceTiers.map((t) => t.name).join(', ')
  const moat = bp.moat

  const ctx = `Context — my business:
• Product: ${product} (${model})
• Target customer: ${audience}
• Core pain solved: ${pain}
• Unique advantage: ${moat}
• Pricing tiers: ${tiers}
• Main channels: ${channels}`

  return [
    {
      id: 'landing',
      title: 'Landing page copy',
      prompt: `${ctx}\n\nWrite high-converting landing page copy for ${product}. Include: a hero headline and subheadline, 3 benefit sections tied to the customer's pain, a short "how it works" (3 steps), social-proof placeholders, an FAQ (5 Qs), and a strong primary call-to-action. Keep the tone confident and clear, aimed at ${audience}.`,
    },
    {
      id: 'sales-call',
      title: 'First sales call script',
      prompt: `${ctx}\n\nWrite a discovery + pitch script for my first sales call with ${audience}. Include: an opening, 6 discovery questions that surface the pain "${pain}", a concise value pitch, how to present pricing (${tiers}), objection handling for the 3 most likely objections, and a clear next-step close.`,
    },
    {
      id: 'content',
      title: '10 content hooks',
      prompt: `${ctx}\n\nGive me 10 scroll-stopping content hooks/post ideas to attract ${audience} and build authority around ${product}. For each: the hook line, the angle, and the single CTA. Mix education, proof, and contrarian takes.`,
    },
    {
      id: 'cold-email',
      title: 'Cold email sequence (3 emails)',
      prompt: `${ctx}\n\nWrite a 3-email cold outreach sequence to ${audience}. Email 1: pattern-interrupt tied to "${pain}". Email 2: proof + soft CTA. Email 3: breakup email. Keep each under 120 words, personal, no jargon, one CTA each.`,
    },
    {
      id: 'brand',
      title: 'Brand & naming kit',
      prompt: `${ctx}\n\nActing as a brand strategist, propose: a one-line positioning statement, 3 tagline options, a brand voice in 3 adjectives with do/don't examples, and 5 alternative product name ideas with rationale. Audience: ${audience}.`,
    },
    {
      id: 'roadmap',
      title: 'Refine my 90-day plan',
      prompt: `${ctx}\n\nHere is my current 90-day plan:\n${bp.roadmap
        .map((p) => `\n${p.title} (${p.window}):\n${p.tasks.map((t) => `- ${t.text}`).join('\n')}`)
        .join('\n')}\n\nReview it as an experienced operator. Point out what's missing, what to cut, the riskiest assumption to test first, and reorder the first two weeks for fastest validation.`,
    },
  ]
}

export function promptPackToMarkdown(bp) {
  const pack = generatePromptPack(bp)
  const lines = [`# ${bp?.concept?.productName || 'Business'} — AI Prompt Pack`, '', '_Paste any prompt into your AI assistant. Generated by Aspir by WTS._', '']
  pack.forEach((p, i) => {
    lines.push(`## ${i + 1}. ${p.title}`, '', '```', p.prompt, '```', '')
  })
  return lines.join('\n')
}
