import React from 'react'
import { useApp } from '../context/AppContext.jsx'
import PrintReport from './PrintReport.jsx'
import { scoreEvaluation, recommendations } from '../engine/evaluation.js'

// Renders exactly one printable report (blueprint / pipeline / evaluation)
// based on context.printTarget. The print stylesheet shows only .print-report.
export default function PrintArea() {
  const { printTarget, activeBlueprint, prospects, evaluation } = useApp()

  if (printTarget === 'pipeline') return <PrintPipeline prospects={prospects} />
  if (printTarget === 'evaluation') return <PrintEvaluation evaluation={evaluation} bp={activeBlueprint} />
  return <PrintReport bp={activeBlueprint} />
}

function PrintPipeline({ prospects = [] }) {
  const won = prospects.filter((p) => p.status === 'Won').length
  return (
    <div className="print-report">
      <h1>Prospect Pipeline</h1>
      <p className="muted">{prospects.length} prospects · {won} won · generated by Aspir by WTS</p>
      <table>
        <thead>
          <tr><th>Company</th><th>Location</th><th>Best contact</th><th>Status</th><th>Fit</th></tr>
        </thead>
        <tbody>
          {prospects.map((p) => (
            <tr key={p.key}>
              <td>{p.name}</td>
              <td>{p.location}</td>
              <td>{p.buyerRole}</td>
              <td>{p.status}</td>
              <td>{p.fit}%</td>
            </tr>
          ))}
          {prospects.length === 0 && <tr><td colSpan={5}>No prospects saved yet.</td></tr>}
        </tbody>
      </table>
    </div>
  )
}

function PrintEvaluation({ evaluation, bp }) {
  const res = scoreEvaluation(evaluation)
  const recs = recommendations(evaluation, 100)
  return (
    <div className="print-report">
      <h1>Business Evaluation{bp?.concept?.productName ? ` — ${bp.concept.productName}` : ''}</h1>
      <p className="muted">Overall health: {res.overall}% ({res.overallBand.label}) · generated by Aspir by WTS</p>

      <h2>Scores by dimension</h2>
      <table>
        <thead><tr><th>Dimension</th><th>Score</th><th>Status</th></tr></thead>
        <tbody>
          {res.dimensions.map((d) => (
            <tr key={d.key}><td>{d.label}</td><td>{d.score}%</td><td>{d.band.label}</td></tr>
          ))}
        </tbody>
      </table>

      <h2>Prioritized improvement ideas</h2>
      <ol>
        {recs.map((r, i) => (
          <li key={i}><strong>[{r.severity}] {r.dimensionLabel}:</strong> {r.fix}</li>
        ))}
        {recs.length === 0 && <li>Everything is rated Good or Excellent — maintain the standard.</li>}
      </ol>
    </div>
  )
}
