import React from 'react'
import { money } from '../engine/blueprintEngine.js'

// Hidden on screen; rendered only when the browser prints (see index.css).
export default function PrintReport({ bp }) {
  if (!bp) return null
  const m = (v) => money(bp.currency, v)
  return (
    <div className="print-report">
      <h1>{bp.concept.productName}</h1>
      <p className="muted">
        Enterprise Blueprint · {bp.modelLabel} · Founder-Market Fit {bp.fitScore}% · Generated by Aspir by WTS
      </p>

      <h2>Executive Summary</h2>
      <p>{bp.execSummary.elevator}</p>
      <h3>Primary revenue streams</h3>
      <ul>{bp.execSummary.revenueStreams.map((r, i) => <li key={i}>{r}</li>)}</ul>
      <h3>Core differentiator</h3>
      <p>{bp.execSummary.differentiator}</p>

      <h2>Target & Value Proposition</h2>
      <p><strong>Audience:</strong> {bp.concept.audience}</p>
      <p><strong>Core pain solved:</strong> {bp.concept.corePain}</p>
      <table>
        <thead><tr><th>Tier</th><th>Price</th><th>Includes</th></tr></thead>
        <tbody>
          {bp.economics.priceTiers.map((t) => (
            <tr key={t.name}><td>{t.name}</td><td>{m(t.price)}{t.cadence}</td><td>{t.features.join('; ')}</td></tr>
          ))}
        </tbody>
      </table>

      <h2>Competitive Advantage</h2>
      <p>{bp.moat}</p>

      <h2>SWOT</h2>
      <table>
        <tbody>
          <tr><th>Strengths</th><td>{bp.swot.strengths.join(' · ')}</td></tr>
          <tr><th>Weaknesses</th><td>{bp.swot.weaknesses.join(' · ')}</td></tr>
          <tr><th>Opportunities</th><td>{bp.swot.opportunities.join(' · ')}</td></tr>
          <tr><th>Threats</th><td>{bp.swot.threats.join(' · ')}</td></tr>
        </tbody>
      </table>

      <h2>Go-To-Market</h2>
      <p><strong>Sales motion:</strong> {bp.gtm.salesMotion}</p>
      <p><strong>First 100 customers:</strong> {bp.gtm.first100}</p>
      <p><strong>Content engine:</strong> {bp.gtm.contentEngine}</p>
      <p><strong>Channels:</strong> {bp.gtm.channels.join(' · ')}</p>

      <h2>Unit Economics</h2>
      <table>
        <tbody>
          <tr><th>CAC</th><td>{m(bp.economics.cac)}</td><th>LTV</th><td>{m(bp.economics.ltv)}</td></tr>
          <tr><th>LTV:CAC</th><td>{bp.economics.ltvCacRatio}:1</td><th>Gross margin</th><td>{Math.round(bp.economics.grossMargin * 100)}%</td></tr>
          <tr><th>Break-even</th><td>Month {bp.economics.breakeven}</td><th>Year-1 gross</th><td>{m(bp.economics.year1Gross)}</td></tr>
        </tbody>
      </table>

      <h2>Risk Mitigation</h2>
      <table>
        <thead><tr><th>Risk</th><th>Severity</th><th>Counter-measure</th></tr></thead>
        <tbody>
          {bp.riskMatrix.map((r, i) => (
            <tr key={i}><td>{r.risk}</td><td>{r.severity}</td><td>{r.mitigation}</td></tr>
          ))}
        </tbody>
      </table>

      <h2>90-Day Roadmap</h2>
      {bp.roadmap.map((phase) => (
        <div key={phase.id}>
          <h3>{phase.title} — {phase.window}</h3>
          <ul>{phase.tasks.map((t) => <li key={t.id}>{t.done ? '☑' : '☐'} {t.text}</li>)}</ul>
        </div>
      ))}
    </div>
  )
}
